using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using QueryNinja.Examples.AspNetCore.DbContext.Entities;

// ReSharper disable StringLiteralTypo
#pragma warning disable 1591

namespace QueryNinja.Examples.AspNetCore.DbContext
{
    [SuppressMessage("ReSharper", "UnusedMember.Global", Justification = "Example of context is no fully utilized")]
    public class UniversityDbContext : Microsoft.EntityFrameworkCore.DbContext
    {
        public UniversityDbContext(DbContextOptions<UniversityDbContext> options)
            : base(options)
        {
        }

        public DbSet<Student> Students { get; set; }
        public DbSet<Exam> Exams { get; set; }
        public DbSet<Grade> Grades { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder
                .Entity<Exam>()
                .HasData(
                    new Exam
                    {
                        Id = 1,
                        Title = "Math"
                    },
                    new Exam
                    {
                        Id = 2,
                        Title = "Physics"
                    },
                    new Exam
                    {
                        Id = 3,
                        Title = "English"
                    }
                );

            // Any coincidences with the real people are accidental
            // Names are generated by https://www.name-generator.org.uk/quick/
            modelBuilder
                .Entity<Student>()
                .HasData(
                    new Student
                    {
                        Id = 1,
                        Name = "Dina Davies"
                    },
                    new Student
                    {
                        Id = 2,
                        Name = "Zayna Rivas"
                    },
                    new Student
                    {
                        Id = 3,
                        Name = "Margo Alcock"
                    },
                    new Student
                    {
                        Id = 4,
                        Name = "Ayden Ashton"
                    },
                    new Student
                    {
                        Id = 5,
                        Name = "Heena Norton"
                    },
                    new Student
                    {
                        Id = 6,
                        Name = "Mica Hills"
                    },
                    new Student
                    {
                        Id = 7,
                        Name = "Roshni Rigby"
                    },
                    new Student
                    {
                        Id = 8,
                        Name = "Quentin Farley"
                    },
                    new Student
                    {
                        Id = 9,
                        Name = "Zubair Hurley"
                    },
                    new Student
                    {
                        Id = 10,
                        Name = "Atlanta Lim"
                    }
                );

            modelBuilder
                .Entity<Grade>()
                .HasData(
                    new Grade
                    {
                        Id = 1,
                        StudentId = 1,
                        ExamId = 1,
                        Mark = Mark.B
                    },
                    new Grade
                    {
                        Id = 2,
                        StudentId = 1,
                        ExamId = 2,
                        Mark = Mark.C
                    },
                    new Grade
                    {
                        Id = 3,
                        StudentId = 3,
                        ExamId = 1,
                        Mark = Mark.A
                    },
                    new Grade
                    {
                        Id = 4,
                        StudentId = 3,
                        ExamId = 2,
                        Mark = Mark.C
                    },
                    new Grade
                    {
                        Id = 5,
                        StudentId = 4,
                        ExamId = 2,
                        Mark = Mark.C
                    },
                    new Grade
                    {
                        Id = 6,
                        StudentId = 4,
                        ExamId = 3,
                        Mark = Mark.F
                    },
                    new Grade
                    {
                        Id = 7,
                        StudentId = 5,
                        ExamId = 2,
                        Mark = Mark.D
                    },
                    new Grade
                    {
                        Id = 8,
                        StudentId = 5,
                        ExamId = 3,
                        Mark = Mark.A
                    },
                    new Grade
                    {
                        Id = 9,
                        StudentId = 6,
                        ExamId = 3,
                        Mark = Mark.B
                    },
                    new Grade
                    {
                        Id = 10,
                        StudentId = 7,
                        ExamId = 1,
                        Mark = Mark.A
                    },
                    new Grade
                    {
                        Id = 11,
                        StudentId = 7,
                        ExamId = 2,
                        Mark = Mark.A
                    },
                    new Grade
                    {
                        Id = 12,
                        StudentId = 7,
                        ExamId = 3,
                        Mark = Mark.A
                    },
                    new Grade
                    {
                        Id = 13,
                        StudentId = 8,
                        ExamId = 1,
                        Mark = Mark.F
                    },
                    new Grade
                    {
                        Id = 14,
                        StudentId = 8,
                        ExamId = 3,
                        Mark = Mark.B
                    },
                    new Grade
                    {
                        Id = 15,
                        StudentId = 9,
                        ExamId = 1,
                        Mark = Mark.C
                    },
                    new Grade
                    {
                        Id = 16,
                        StudentId = 9,
                        ExamId = 2,
                        Mark = Mark.A
                    },
                    new Grade
                    {
                        Id = 17,
                        StudentId = 9,
                        ExamId = 3,
                        Mark = Mark.B
                    },
                    new Grade
                    {
                        Id = 18,
                        StudentId = 10,
                        ExamId = 1,
                        Mark = Mark.C
                    },
                    new Grade
                    {
                        Id = 19,
                        StudentId = 10,
                        ExamId = 2,
                        Mark = Mark.B
                    },
                    new Grade
                    {
                        Id = 20,
                        StudentId = 10,
                        ExamId = 3,
                        Mark = Mark.D
                    }
                );
        }
    }
}