FROM mcr.microsoft.com/dotnet/sdk:5.0 AS builder
WORKDIR /source

COPY . .
RUN dotnet restore QueryNinja.sln
RUN dotnet publish ./QueryNinja.Examples.AspNetCore/QueryNinja.Examples.AspNetCore.csproj --output /app/ --configuration Release

FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine
WORKDIR /app
COPY --from=builder /app .
ENV ASPNETCORE_URLS http://*:$PORT
ENTRYPOINT ["dotnet", "QueryNinja.Examples.AspNetCore.dll"]
