// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryNinja.Examples.AspNetCore.DbContext;

namespace QueryNinja.Examples.AspNetCore.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20201229230601_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("QueryNinja.Examples.AspNetCore.DbContext.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Title = "English"
                        });
                });

            modelBuilder.Entity("QueryNinja.Examples.AspNetCore.DbContext.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mark")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExamId = 1,
                            Mark = 4,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExamId = 2,
                            Mark = 3,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExamId = 1,
                            Mark = 5,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            ExamId = 2,
                            Mark = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 5,
                            ExamId = 2,
                            Mark = 3,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 6,
                            ExamId = 3,
                            Mark = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 7,
                            ExamId = 2,
                            Mark = 2,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 8,
                            ExamId = 3,
                            Mark = 5,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 9,
                            ExamId = 3,
                            Mark = 4,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 10,
                            ExamId = 1,
                            Mark = 5,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 11,
                            ExamId = 2,
                            Mark = 5,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 12,
                            ExamId = 3,
                            Mark = 5,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 13,
                            ExamId = 1,
                            Mark = 1,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 14,
                            ExamId = 3,
                            Mark = 4,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 15,
                            ExamId = 1,
                            Mark = 3,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 16,
                            ExamId = 2,
                            Mark = 5,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 17,
                            ExamId = 3,
                            Mark = 4,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 18,
                            ExamId = 1,
                            Mark = 3,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 19,
                            ExamId = 2,
                            Mark = 4,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 20,
                            ExamId = 3,
                            Mark = 2,
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("QueryNinja.Examples.AspNetCore.DbContext.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dina Davies"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zayna Rivas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Margo Alcock"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ayden Ashton"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Heena Norton"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mica Hills"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Roshni Rigby"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Quentin Farley"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Zubair Hurley"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Atlanta Lim"
                        });
                });

            modelBuilder.Entity("QueryNinja.Examples.AspNetCore.DbContext.Entities.Grade", b =>
                {
                    b.HasOne("QueryNinja.Examples.AspNetCore.DbContext.Entities.Exam", "Exam")
                        .WithMany("Grades")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueryNinja.Examples.AspNetCore.DbContext.Entities.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QueryNinja.Examples.AspNetCore.DbContext.Entities.Exam", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("QueryNinja.Examples.AspNetCore.DbContext.Entities.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
