# Contains main CI pipelines for packages.
name: Main CI for Package and Code Quality

on:
  push:
    branches: 
      - release/v*
      - hotfix/v*
      - develop
    tags:
      - v*
  pull_request:
    branches: 
      - develop    
jobs:
  build_n_test:
    name: Build & Test
    runs-on: ubuntu-latest   
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
    steps:
    - uses: actions/checkout@v2   
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Define package version
      id: package_version
      if: ${{github.event_name == 'push'}}
      run: |
        shortSha=$(git rev-parse --short ${{ github.ref }})
        version=$(echo ${{ github.ref }} | cut -d'v' -f 2-)
        if ${{ github.ref == 'refs/heads/develop' }};
        then        
            echo ::set-output name=version::"0.0.1-develop.${shortSha}"
        elif ${{ startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/') }};
        then           
            echo ::set-output name=version::"${version}-rc.${shortSha}"
        elif ${{ startsWith(github.ref, 'refs/tags/v') }}
        then
            echo ::set-output name=version::$version
        fi
      
    - name: Nuget Pack
      if: ${{github.event_name == 'push'}}
      run: dotnet pack --include-symbols --no-restore --output ./nuget --configuration Release -p:PackageVersion=$CI_PACKAGE_VERSION
      env:
        CI_PACKAGE_VERSION: ${{steps.package_version.outputs.version}}
        
    - name: Archive NuGet packages
      if: ${{github.event_name == 'push'}}
      uses: actions/upload-artifact@v2
      with:
        name: NuGet Packages
        path: ./nuget 
        
    - name: Run Benchmarking
      if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
      run: dotnet run -c Release --project .\QueryNinja.Benchmarking\QueryNinja.Benchmarking.csproj --filter * --maxIterationCount 50
      
    - name: Archive Benchmarking Results
      if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
      with:
        name: Benchmarking Results
        path: ./QueryNinja.Benchmarking/bin/Release/net5.0/BenchmarkDotNet.Artifacts
    
    
  nuget_push:
    name: Nuget Push
    runs-on: ubuntu-latest   
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
    needs: [build_n_test]
    environment: NuGet
    if: ${{github.event_name == 'push'}}
    steps:
      - name: Get NuGet Packages
        uses: actions/download-artifact@v2
        with:
          name: NuGet Packages
          path: ./nuget
          
      - name: Push Packages
        run: dotnet nuget push "./nuget/*.symbols.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        
  heroku_deploy:
    name: Deploy Example to Heroku
    runs-on: ubuntu-latest 
    needs: [build_n_test]
    environment: Heroku
    if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')}}
    env:
      HEROKU_IMAGE_NAME: "registry.heroku.com/query-ninja/web"
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2 
      - name: Build image
        run: docker build . --file "./QueryNinja.Examples.AspNetCore/DOCKERFILE" --tag $HEROKU_IMAGE_NAME
      - name: Heroku Build
        run: |
          heroku container:login
          docker push $HEROKU_IMAGE_NAME
      - name: Heroku Release
        run: heroku container:release -a query-ninja web 
    
    
        
  
  
    
